version: '2'
services: 
  web:
    build:
      command: npm i && node server.js
      depends_on:
        - postgres
        - redis
        - elasticsearch
      environment:
        NODE_APP_DEBUG: 'info'
        ports:
          - '1337:1337'
      volumes:
        - './videos_api:/var/app'
  postgres:
    image: postgres:13
    volumes:
      - './database/init.sql:/docker-entrypoint-initdb.d/init.sql'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200'