SELECT 'CREATE DATABASE videos'
WHERE NOT EXISTS (SELECT FROM videos WHERE datname = 'videos')\gexec;
CREATE USER benjamin WITH PASSWORD 'root1337489417';
GRANT ALL PRIVILEGES ON DATABASE "videos" to benjamin;